# =====================================
# Builder Stage
# =====================================
FROM node:24-alpine AS builder

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate --schema=./prisma/schema/schema.prisma

RUN npm run build

# =====================================
# Production Stage
# =====================================
FROM node:24-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./

RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

COPY --from=builder /app/prisma ./prisma

RUN npx prisma generate --schema=./prisma/schema/schema.prisma

EXPOSE 3000

CMD ["node", "dist/src/index.js"]